server:
  port: 86
  max-http-header-size: 10240

guns:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations: classpath:cn/stylefeng/guns/modular/**/mapping/*.xml,classpath:org/flowable/ui/common/security/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

log:
  path: guns-logs

flowable:
  async-executor-activate: false
  database-schema-update: true